import React from 'react';
import { ArrowDownTrayIcon, BriefcaseIcon, ChatBubbleLeftRightIcon, FilmIcon, LockClosedIcon, MicrophoneIcon, SparklesIcon, UserGroupIcon, VideoCameraIcon } from '@heroicons/react/24/outline';

const FEATURES = [
    ['social', UserGroupIcon, 'Social — a feed you control', 'CHEETCHAT Social is built around user choice. People can create posts, share photos and videos, write articles, comment, reply, react, follow creators, build communities and choose the feed they want to see. Instead of forcing a single opaque algorithmic timeline, Social offers customizable feed controls so users can shape their own experience, discover relevant voices and decide which content categories and communities matter to them.'],
    ['reels', FilmIcon, 'Reels — create, discover and react live', 'Users can record or upload vertical reels, add captions, publish their ideas, discover creators and choose a customizable reels feed. Likes, comments, replies, sharing, creator profiles and view activity make every reel interactive. Live reactions let viewers respond while an existing reel is playing. Autoplay, sound and data-saver controls allow each user to decide how reels behave on their device.'],
    ['chat', ChatBubbleLeftRightIcon, 'Advanced private messaging', 'Chat combines direct messages, groups, replies, reactions, emoji, GIFs, voice notes, files, photos, video, calls, message search, pinned messages, smart replies and conversation summaries. Presence controls support online and last-seen visibility, including the choice to hide them. Users can identify messages that still need a reply and find important information without manually reading an entire long chat.'],
    ['security', LockClosedIcon, 'End-to-end encryption and privacy', 'Private message content uses hybrid end-to-end encryption: a fresh AES-GCM content key protects each message, and that key is wrapped separately for participants using their public encryption keys. Safety numbers allow two people to compare and verify their encryption keys. Encrypted media is protected before upload, while real-time calls use secure WebRTC media transport. Story privacy, profile-photo visibility, contact-specific special DPs, read receipts, blocking and reporting provide additional control.'],
    ['design', SparklesIcon, 'Personalized chat expression and design', 'Every conversation can feel personal through customizable themes, wallpapers, chat colors, fonts and animated UI options. Users can create an avatar manually or generate one from a picture, then use avatar-based reactions in chat. Photo reactions can happen in real time, and drawing tools let people annotate a picture or send an original drawn message. Built-in translation helps conversations cross language barriers, while birthday reminders and greeting experiences make important moments harder to miss.'],
    ['snap', VideoCameraIcon, 'Snap Mode and disappearing messages', 'Disappearing-message controls allow a sender or chat to use a selected lifetime for temporary content. Snap Mode creates a more private session in which supported messages and media disappear for participants after the session ends. The interface communicates temporary-message behavior, restricts common forwarding and download actions where supported, and applies the chat’s expiry rules to messages and media. No disappearing system can prevent another person from recording a screen with a second device, so users should still share carefully.'],
    ['podlive', MicrophoneIcon, 'PodLive, podcasts and live participation', 'PodLive lets creators start podcast-style live rooms with real-time chat. Hosts can invite people from a live audience, randomly pick a viewer and bring that person into talk mode for a spontaneous conversation. Creators can report news directly in the app, share invitations in chat and move between listening, viewing and participating without leaving CHEETCHAT.'],
    ['channels', VideoCameraIcon, 'Channels, public video and creator ownership', 'Creators can build and customize a channel, upload videos, publish ideas and manage their own content library. Public videos can be discovered and watched by the wider community, while viewers can customize the type of video feed they prefer. Channel owners retain control over uploads and can use supported paid-content tools to sell access to eligible videos and earn directly from their work. Payments and monetization depend on account eligibility and deployment configuration.'],
    ['ai', SparklesIcon, 'AI chat and personal assistance', 'The in-app AI companion supports personal conversation, brainstorming, study help, writing, explanations and everyday planning. AI-powered tools can help summarize long conversations, improve grammar, suggest replies and make information easier to find. AI output may be inaccurate, so important academic, financial, medical or legal information should always be checked independently.'],
    ['business', BriefcaseIcon, 'Business tools and digital storefronts', 'Businesses can create a professional profile, add a product catalog, display stock and pricing information and open a digital storefront inside CHEETCHAT. Welcome messages, away messages and keyword-based automated replies help answer common customer questions, while conversation, catalog, profile-view and auto-reply analytics help owners understand activity. Small businesses can present products, communicate with customers and manage routine support from one app.']
];

const Fact = ({ value, label }) => <div className="rounded-2xl bg-black/20 p-3 text-center"><p className="text-xl font-black text-white">{value}</p><p className="mt-1 text-[11px] text-gray-400">{label}</p></div>;

const AboutCheetChat = ({ compact = false }) => <div className={compact ? 'space-y-5 p-5' : 'space-y-8'}>
    <section className="rounded-3xl border border-violet-400/20 bg-gradient-to-br from-violet-500/20 via-blue-500/10 to-emerald-500/10 p-6">
        <p className="text-xs font-black uppercase tracking-[0.22em] text-violet-300">All in one. Made for India.</p>
        <h1 className="mt-2 text-2xl font-black text-white sm:text-3xl">CHEETCHAT — an all-in-one platform dedicated to Indian users and college students</h1>
        <p className="mt-4 text-sm leading-7 text-gray-300">CHEETCHAT brings private communication, creator tools, social discovery, short video, podcasts, public channels, AI assistance and digital business tools into one connected experience. It helps students, communities, creators and small businesses communicate, learn, publish and grow without constantly switching between apps.</p>
        <div className="mt-5 grid gap-3 sm:grid-cols-3"><Fact value="1,000+" label="registered users*" /><Fact value="100–200" label="daily visits*" /><Fact value="India" label="designed and developed" /></div>
        <p className="mt-3 text-[10px] leading-4 text-gray-500">*Community figures supplied by the CHEETCHAT team as of August 2026; approximate and subject to change.</p>
    </section>
    <section className="rounded-3xl border border-[#00a884]/30 bg-[#00a884]/10 p-6 text-center">
        <span className="inline-flex rounded-full border border-emerald-300/25 bg-emerald-300/10 px-3 py-1 text-xs font-black uppercase tracking-wider text-emerald-300">Android Beta Available</span>
        <h2 className="mt-3 text-xl font-black text-white">Take CHEETCHAT with you</h2>
        <p className="mx-auto mt-2 max-w-2xl text-sm leading-7 text-gray-300">The CHEETCHAT Android app is currently available as a beta release. You can download the latest APK, try the mobile experience and help improve the app before its wider release.</p>
        <a href="https://docs.google.com/uc?export=download&id=1Ljn280n5VmWfD1kEl7u_AAyZ-2S6L1s9" target="_blank" rel="noopener noreferrer" className="mt-5 inline-flex items-center justify-center gap-2 rounded-xl bg-[#00a884] px-6 py-3.5 text-sm font-black text-white shadow-lg shadow-[#00a884]/20 transition hover:bg-[#06bd96]"><ArrowDownTrayIcon className="h-5 w-5" /> Download Android Beta</a>
        <p className="mt-3 text-[11px] leading-5 text-gray-500">This is a beta build and may contain unfinished features. Android may ask you to allow installation from your browser; install only from this official CHEETCHAT link.</p>
    </section>
    <section className="grid gap-4">{FEATURES.map(([id, Icon, title, text]) => <article id={id} key={id} className="rounded-2xl border border-white/10 bg-white/[0.04] p-5"><div className="flex items-start gap-3"><span className="rounded-xl bg-[#00a884]/15 p-2.5 text-[#53d8b3]"><Icon className="h-5 w-5" /></span><div><h2 className="font-black text-white">{title}</h2><p className="mt-2 text-sm leading-7 text-gray-400">{text}</p></div></div></article>)}</section>
    <section className="rounded-2xl border border-amber-400/20 bg-amber-400/5 p-5"><h2 className="font-black text-amber-200">Learning and entertainment discovery</h2><p className="mt-2 text-sm leading-7 text-gray-400">Through creator posts, channels, public videos and customizable feeds, the community can discover educational courses, student resources, ideas, parent-focused content, entertainment and movies that eligible creators or publishers lawfully make available. CHEETCHAT does not claim ownership of third-party content, and availability depends on creators, licensing, moderation and regional rules.</p></section>
    <footer className="rounded-2xl bg-black/20 p-5 text-center"><p className="text-xs uppercase tracking-widest text-gray-500">Founder</p><p className="mt-1 text-lg font-black text-white">Amitesh Kumar Yadav</p><a href="https://chat.indiasearch.site" className="mt-3 inline-block text-sm font-bold text-[#53d8b3] hover:underline">chat.indiasearch.site</a></footer>
</div>;

export default AboutCheetChat;
