import React, { useCallback, useEffect, useState } from 'react';
import { ArrowLeftIcon, ArrowPathIcon, MagnifyingGlassIcon, MicrophoneIcon, PlayIcon, SignalIcon, UserGroupIcon } from '@heroicons/react/24/outline';
import usePodLiveSession from './auth/usePodLiveSession';
import { podlive, unwrapApiError } from './api/podliveApi';
import { PODLIVE_CATEGORIES } from './config';

const LiveRoom = React.lazy(() => import('./components/LiveRoom'));
let feedCache = [];
const avatarFor = (user) => user?.avatar_url || `https://ui-avatars.com/api/?name=${encodeURIComponent(user?.display_name || 'P')}&background=6366f1&color=fff`;
const Loading = ({ label }) => <div className="grid min-h-48 place-items-center"><div className="text-center"><ArrowPathIcon className="mx-auto h-7 w-7 animate-spin text-indigo-400"/><p className="mt-3 text-sm text-zinc-500">{label}</p></div></div>;
const Empty = ({ text }) => <div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-sm text-zinc-500">{text}</div>;
const ErrorBox = ({ text, retry }) => <div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{text}{retry && <button onClick={retry} className="ml-3 font-bold underline">Try again</button>}</div>;
const Field = ({ label, ...props }) => <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400">{label}<input {...props} className="mt-2 w-full rounded-xl border border-white/10 bg-zinc-900 px-4 py-3 text-sm text-white outline-none focus:border-indigo-500"/></label>;

function LiveCard({ session, open }) {
    return <button onClick={() => open('live', session.id)} className="group min-w-0 text-left"><div className="relative aspect-video overflow-hidden rounded-xl border border-white/[.07] bg-zinc-900 transition group-hover:border-red-500/40">{session.thumbnail_url ? <img src={session.thumbnail_url} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/> : <div className="absolute inset-0 grid place-items-center bg-gradient-to-br from-zinc-900 to-zinc-950"><SignalIcon className="h-10 w-10 text-zinc-700"/></div>}<span className="absolute left-2 top-2 rounded bg-red-600 px-2 py-1 text-[10px] font-black">● LIVE</span><span className="absolute right-2 top-2 rounded bg-black/70 px-2 py-1 text-[10px] font-bold">{session.viewer_count || session.viewer_count_peak || 0} watching</span><span className="absolute inset-0 grid place-items-center bg-black/35 opacity-0 transition group-hover:opacity-100"><span className="grid h-12 w-12 place-items-center rounded-full bg-white/20 backdrop-blur"><PlayIcon className="h-6 w-6"/></span></span></div><div className="mt-3 flex gap-3"><img src={avatarFor(session.host)} alt="" className="h-9 w-9 shrink-0 rounded-full object-cover"/><div className="min-w-0"><p className="line-clamp-2 text-sm font-semibold group-hover:text-indigo-400">{session.title}</p><p className="mt-1 truncate text-xs text-zinc-500">{session.host?.unique_handle || session.host?.display_name}</p><p className="text-[11px] font-medium text-red-400">Live now · {session.category || 'General'}</p></div></div></button>;
}

function Browse({ open }) {
    const [lives, setLives] = useState(feedCache); const [loading, setLoading] = useState(!feedCache.length); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All');
    const load = useCallback(async () => { try { const next = await podlive.active(); feedCache = next; setLives(next); setError(''); } catch (err) { setError(unwrapApiError(err, 'Live feed is temporarily unavailable.')); } finally { setLoading(false); } }, []);
    useEffect(() => { load(); const timer = setInterval(load, 8000); return () => clearInterval(timer); }, [load]);
    const visible = lives.filter((item) => (category === 'All' || item.category === category) && `${item.title} ${item.host?.display_name || ''}`.toLowerCase().includes(query.toLowerCase()));
    return <div className="mx-auto max-w-7xl p-4 pb-24 md:p-6"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-xl font-black">Live now</h1><p className="text-xs text-zinc-500">Real-time conversations from your community</p></div><div className="flex gap-2"><div className="relative flex-1"><MagnifyingGlassIcon className="absolute left-3 top-2.5 h-4 w-4 text-zinc-500"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search live" className="w-full rounded-full border border-white/10 bg-zinc-900 py-2 pl-9 pr-4 text-sm outline-none focus:border-indigo-500"/></div><button onClick={() => open('create')} className="whitespace-nowrap rounded-full bg-red-600 px-5 py-2 text-xs font-black hover:bg-red-500">Go Live</button></div></div><div className="mb-6 flex gap-2 overflow-x-auto pb-1">{['All', ...PODLIVE_CATEGORIES].map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${category === item ? 'bg-indigo-600 text-white' : 'bg-white/5 text-zinc-400 hover:bg-white/10'}`}>{item}</button>)}</div>{error && <div className="mb-5"><ErrorBox text={error} retry={load}/></div>}{loading ? <Loading label="Loading live rooms…"/> : visible.length ? <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visible.map((session) => <LiveCard key={session.id} session={session} open={open}/>)}</div> : <Empty text="No live rooms right now. Start the first conversation."/>}</div>;
}

function Viewer({ id, back }) {
    const [state, setState] = useState({ loading: true, room: null, details: null, error: '' });
    const connect = useCallback(async () => { setState((current) => ({ ...current, loading: true, error: '' })); try { const [room, details] = await Promise.all([podlive.viewerToken(id), podlive.details(id)]); setState({ loading: false, room, details, error: '' }); } catch (error) { const ended = error?.response?.status === 404; setState({ loading: false, room: null, details: null, error: ended ? 'This live room has ended.' : unwrapApiError(error) }); } }, [id]);
    useEffect(() => { connect(); }, [connect]);
    if (state.loading) return <Loading label="Joining live room…"/>;
    if (state.error) return <div className="mx-auto max-w-xl p-5"><ErrorBox text={state.error} retry={state.error.includes('ended') ? back : connect}/></div>;
    return <div className="flex h-full min-h-0 flex-col bg-black"><div className="flex h-14 shrink-0 items-center justify-between border-b border-white/10 px-3"><button onClick={back} className="flex items-center gap-2 text-sm text-zinc-300"><ArrowLeftIcon className="h-4 w-4"/>Live feed</button><span className="rounded bg-red-600 px-2 py-1 text-[10px] font-black">● LIVE</span></div><div className="min-h-0 flex-1"><React.Suspense fallback={<Loading label="Connecting…"/>}><LiveRoom token={state.room.token} serverUrl={state.room.livekitUrl} onDisconnected={back}/></React.Suspense></div><div className="shrink-0 border-t border-white/10 p-3"><h2 className="truncate font-bold">{state.details?.title}</h2><p className="text-xs text-zinc-500">{state.details?.host?.display_name}</p></div></div>;
}

function Studio({ id, back }) {
    const [state, setState] = useState({ room: null, loading: true, error: '' });
    const connect = useCallback(async () => { setState({ room: null, loading: true, error: '' }); try { setState({ room: await podlive.start(id), loading: false, error: '' }); } catch (error) { setState({ room: null, loading: false, error: unwrapApiError(error) }); } }, [id]);
    useEffect(() => { connect(); }, [connect]);
    const end = async () => { try { await podlive.end(id); } finally { feedCache = []; back(); } };
    if (state.loading) return <Loading label="Preparing camera and microphone…"/>;
    if (state.error) return <div className="mx-auto max-w-xl p-5"><ErrorBox text={state.error} retry={connect}/></div>;
    return <div className="flex h-full min-h-0 flex-col bg-black"><div className="flex h-14 shrink-0 items-center justify-between border-b border-white/10 px-3"><span className="font-black text-red-500">● LIVE</span><button onClick={end} className="rounded-full bg-red-600 px-4 py-2 text-xs font-black">End live</button></div><div className="min-h-0 flex-1"><React.Suspense fallback={<Loading label="Opening studio…"/>}><LiveRoom token={state.room.token} serverUrl={state.room.livekitUrl} publisher onDisconnected={() => setState((current) => ({ ...current, error: 'Connection lost. Rejoin the same live room.' }))}/></React.Suspense></div></div>;
}

function Create({ open }) {
    const [values, setValues] = useState({ title: '', description: '', category: 'Technology' }); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
    const submit = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const result = await podlive.create({ ...values, goLiveNow: true, dvr_enabled: false }); open('studio', result.session.id); } catch (err) { setError(unwrapApiError(err)); setBusy(false); } };
    return <div className="mx-auto max-w-2xl p-4 pb-24 md:p-8"><h1 className="mb-6 text-2xl font-black">Start live</h1><form onSubmit={submit} className="space-y-5 rounded-3xl border border-white/10 bg-white/[.04] p-5 md:p-7">{error && <ErrorBox text={error}/>}<Field label="Title" required maxLength="120" value={values.title} onChange={(event) => setValues({...values, title:event.target.value})}/><label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400">Description<textarea rows="4" maxLength="1000" value={values.description} onChange={(event) => setValues({...values, description:event.target.value})} className="mt-2 w-full resize-none rounded-xl border border-white/10 bg-zinc-900 p-4 text-sm text-white outline-none focus:border-indigo-500"/></label><label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400">Category<select value={values.category} onChange={(event) => setValues({...values, category:event.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-zinc-900 p-3 text-sm text-white">{PODLIVE_CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select></label><p className="text-xs text-zinc-500">Live is real-time only. Nothing is recorded or stored.</p><button disabled={busy} className="w-full rounded-xl bg-red-600 py-3 font-black disabled:opacity-50">{busy ? 'Starting…' : 'Go Live'}</button></form></div>;
}

function Dashboard({ open }) {
    const [stats, setStats] = useState(null); useEffect(() => { podlive.stats().then(setStats).catch(() => setStats({})); }, []);
    const cards = [['Followers', stats?.followers], ['Total views', stats?.totalViews], ['Live sessions', stats?.totalLives]];
    return <div className="mx-auto max-w-6xl space-y-7 p-4 pb-24 md:p-7"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black">Creator Studio</h1><p className="text-xs text-zinc-500">Manage your real-time presence</p></div><button onClick={() => open('create')} className="rounded-full bg-red-600 px-5 py-2 text-xs font-black">Go Live</button></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-3">{cards.map(([label,value]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><p className="text-xs uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-2 text-2xl font-black">{Number(value || 0).toLocaleString()}</p></div>)}</div><Empty text="PodLive is real-time only. Recordings and uploads are disabled."/></div>;
}

export default function PodLiveApp({ active, onBack }) {
    const session = usePodLiveSession(active); const [route, setRoute] = useState({ name: 'browse', id: null }); const open = (name, id = null) => setRoute({ name, id });
    if (!active) return null;
    const content = route.name === 'browse' ? <Browse open={open}/> : route.name === 'live' ? <Viewer id={route.id} back={() => open('browse')}/> : route.name === 'studio' ? <Studio id={route.id} back={() => open('dashboard')}/> : route.name === 'create' ? <Create open={open}/> : <Dashboard open={open}/>;
    if (session.loading && !session.user) return <div className="h-full bg-[#080808] text-white"><Loading label="Opening PodLive…"/></div>;
    if (session.error && !session.user) return <div className="grid h-full place-items-center bg-[#080808] p-4 text-white"><ErrorBox text={session.error} retry={session.retry}/></div>;
    if (route.name === 'studio' || route.name === 'live') return <div className="h-full bg-black text-white">{content}</div>;
    return <div className="flex h-full flex-col overflow-hidden bg-[#080808] text-white"><header className="flex h-14 shrink-0 items-center gap-3 border-b border-white/[.07] bg-[#080808]/95 px-3 backdrop-blur md:px-5"><button onClick={onBack} className="rounded-full p-2 hover:bg-white/10" title="Back"><ArrowLeftIcon className="h-5 w-5"/></button><button onClick={() => open('browse')} className="flex items-center gap-2 font-black"><span className="grid h-8 w-8 place-items-center rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600"><MicrophoneIcon className="h-4 w-4"/></span><span>PodLive</span></button><nav className="ml-auto flex items-center gap-1"><button onClick={() => open('browse')} className="rounded-full px-3 py-2 text-xs font-bold hover:bg-white/10"><SignalIcon className="inline h-4 w-4 sm:mr-1"/><span className="hidden sm:inline">Explore</span></button><button onClick={() => open('dashboard')} className="rounded-full px-3 py-2 text-xs font-bold hover:bg-white/10"><UserGroupIcon className="inline h-4 w-4 sm:mr-1"/><span className="hidden sm:inline">Studio</span></button><img src={avatarFor(session.user)} alt="" className="ml-1 h-8 w-8 rounded-full object-cover"/></nav></header><main className="min-h-0 flex-1 overflow-y-auto">{content}</main></div>;
}
