import React, { useCallback, useEffect, useState } from 'react';
import axios from 'axios';
import { AdjustmentsHorizontalIcon, ArrowLeftIcon, ArrowPathIcon, ChatBubbleLeftRightIcon, EyeIcon, MagnifyingGlassIcon, MicrophoneIcon, PlayIcon, ShareIcon, SignalIcon, UserGroupIcon, VideoCameraIcon, XMarkIcon } from '@heroicons/react/24/outline';
import usePodLiveSession from './auth/usePodLiveSession';
import { podlive, unwrapApiError } from './api/podliveApi';
import { PODLIVE_CATEGORIES } from './config';
import usePodLiveSocket from './hooks/usePodLiveSocket';

const LiveRoom = React.lazy(() => import('./components/LiveRoom'));
const UploadedVideoPlayer = React.lazy(() => import('./components/UploadedVideoPlayer'));
let feedCache = [];
const avatarFor = (user) => user?.avatar_url || `https://ui-avatars.com/api/?name=${encodeURIComponent(user?.display_name || 'P')}&background=6366f1&color=fff`;
const Loading = ({ label }) => <div className="grid min-h-48 place-items-center"><div className="text-center"><ArrowPathIcon className="mx-auto h-7 w-7 animate-spin text-indigo-400"/><p className="mt-3 text-sm text-zinc-500">{label}</p></div></div>;
const Empty = ({ text }) => <div className="rounded-2xl border border-dashed border-white/10 p-10 text-center text-sm text-zinc-500">{text}</div>;
const ErrorBox = ({ text, retry }) => <div className="rounded-2xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">{text}{retry && <button onClick={retry} className="ml-3 font-bold underline">Try again</button>}</div>;
const Field = ({ label, ...props }) => <label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400">{label}<input {...props} className="mt-2 w-full rounded-xl border border-white/10 bg-zinc-900 px-4 py-3 text-sm text-white outline-none focus:border-indigo-500"/></label>;

function LiveCard({ session, open }) {
    return <button onClick={() => open('live', session.id)} className="group min-w-0 text-left"><div className="relative aspect-video overflow-hidden rounded-xl border border-white/[.07] bg-zinc-900 transition group-hover:border-red-500/40">{session.thumbnail_url ? <img src={session.thumbnail_url} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/> : <div className="absolute inset-0 grid place-items-center bg-gradient-to-br from-zinc-900 to-zinc-950"><SignalIcon className="h-10 w-10 text-zinc-700"/></div>}<span className="absolute left-2 top-2 rounded bg-red-600 px-2 py-1 text-[10px] font-black">● LIVE</span><span className="absolute right-2 top-2 rounded bg-black/70 px-2 py-1 text-[10px] font-bold">{session.viewer_count || session.viewer_count_peak || 0} watching</span><span className="absolute inset-0 grid place-items-center bg-black/35 opacity-0 transition group-hover:opacity-100"><span className="grid h-12 w-12 place-items-center rounded-full bg-white/20 backdrop-blur"><PlayIcon className="h-6 w-6"/></span></span></div><div className="mt-3 flex gap-3"><img src={avatarFor(session.host)} alt="" className="h-9 w-9 shrink-0 rounded-full object-cover"/><div className="min-w-0"><p className="line-clamp-2 text-sm font-semibold group-hover:text-indigo-400">{session.title}</p><p className="mt-1 truncate text-xs text-zinc-500">{session.host?.unique_handle || session.host?.display_name}</p><p className="text-[11px] font-medium text-red-400">Live now · {session.category || 'General'}</p></div></div></button>;
}

function VideoCard({ video, open }) {
    return <button onClick={() => open('video', video.id)} className="group min-w-0 text-left"><div className="relative aspect-video overflow-hidden rounded-xl bg-zinc-900">{video.thumbnail_url && <img src={video.thumbnail_url} alt="" className="h-full w-full object-cover"/>}<span className="absolute inset-0 grid place-items-center bg-black/25"><span className="grid h-11 w-11 place-items-center rounded-full bg-white/20"><PlayIcon className="h-5 w-5"/></span></span></div><p className="mt-2 line-clamp-2 text-sm font-bold">{video.title}</p><p className="text-xs text-zinc-500">{video.host?.display_name} · {Number(video.views || video.viewer_count_peak || 0).toLocaleString()} views · {video.like_count || 0} likes</p></button>;
}

function Browse({ open }) {
    const [lives, setLives] = useState(feedCache); const [videos, setVideos] = useState([]); const [loading, setLoading] = useState(!feedCache.length); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All');
    const load = useCallback(async () => { try { const [next, uploaded] = await Promise.all([podlive.active(), podlive.videos()]); feedCache = next; setLives(next); setVideos(uploaded); setError(''); } catch (err) { setError(unwrapApiError(err, 'PodLive feed is temporarily unavailable.')); } finally { setLoading(false); } }, []);
    useEffect(() => { load(); const refresh = () => load(); window.addEventListener('podlive:started', refresh); window.addEventListener('podlive:ended', refresh); const timer = setInterval(load, 4000); return () => { clearInterval(timer); window.removeEventListener('podlive:started', refresh); window.removeEventListener('podlive:ended', refresh); }; }, [load]);
    const visible = lives.filter((item) => (category === 'All' || item.category === category) && `${item.title} ${item.host?.display_name || ''}`.toLowerCase().includes(query.toLowerCase()));
    return <div className="mx-auto max-w-7xl space-y-9 p-4 pb-24 md:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><h1 className="text-xl font-black">PodLive</h1><p className="text-xs text-zinc-500">Live conversations and creator videos</p></div><div className="flex gap-2"><div className="relative flex-1"><MagnifyingGlassIcon className="absolute left-3 top-2.5 h-4 w-4 text-zinc-500"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search" className="w-full rounded-full border border-white/10 bg-zinc-900 py-2 pl-9 pr-4 text-sm outline-none"/></div><button onClick={() => open('create')} className="whitespace-nowrap rounded-full bg-red-600 px-5 py-2 text-xs font-black">Go Live</button></div></div><div className="flex gap-2 overflow-x-auto">{['All', ...PODLIVE_CATEGORIES].map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-bold ${category === item ? 'bg-indigo-600' : 'bg-white/5 text-zinc-400'}`}>{item}</button>)}</div>{error && <ErrorBox text={error} retry={load}/>}<section><h2 className="mb-4 text-lg font-black">Live now</h2>{loading ? <Loading label="Loading…"/> : visible.length ? <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visible.map((item) => <LiveCard key={item.id} session={item} open={open}/>)}</div> : <Empty text="No one is live right now."/>}</section><section><h2 className="mb-4 text-lg font-black">Latest videos</h2>{videos.length ? <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{videos.filter((item) => `${item.title} ${item.host?.display_name || ''}`.toLowerCase().includes(query.toLowerCase())).map((item) => <VideoCard key={item.id} video={item} open={open}/>)}</div> : <Empty text="No uploaded videos yet."/>}</section></div>;
}

function ChatPanel({ realtime, overlay = false, onClose }) {
    const [message, setMessage] = useState('');
    const send = (event) => { event.preventDefault(); if (!message.trim()) return; realtime.sendMessage(message); setMessage(''); };
    return <aside className={`flex min-h-0 flex-col border-white/10 ${overlay ? 'absolute inset-x-3 bottom-3 z-30 max-h-[52%] rounded-2xl border bg-black/55 shadow-2xl backdrop-blur-md md:left-auto md:w-96' : 'w-full border-t bg-zinc-950 md:w-80 md:border-l md:border-t-0'}`}><div className="flex items-center justify-between border-b border-white/10 p-3 text-sm font-black"><span>Live chat</span>{onClose&&<button onClick={onClose} aria-label="Hide live chat" className="rounded-full p-1 hover:bg-white/10"><XMarkIcon className="h-4 w-4"/></button>}</div><div className="min-h-20 flex-1 space-y-3 overflow-y-auto p-3">{realtime.messages.length ? realtime.messages.map((item, index) => <div key={`${item.created_at}-${index}`} className="text-sm drop-shadow"><span className="mr-2 font-bold text-indigo-300">{item.senderHandle}</span><span className="text-white">{item.message}</span></div>) : <p className="text-xs text-zinc-500">Chat messages will appear here.</p>}</div><form onSubmit={send} className="flex gap-2 border-t border-white/10 p-3"><input value={message} maxLength="500" onChange={(e) => setMessage(e.target.value)} placeholder="Say something" className="min-w-0 flex-1 rounded-full bg-zinc-900/90 px-3 py-2 text-sm outline-none"/><button className="rounded-full bg-indigo-600 px-3 text-xs font-bold">Send</button></form></aside>;
}

let shareInProgress = false;
const shareLive = async (id, title) => {
    if (shareInProgress) return;
    const url = `${window.location.origin}${window.location.pathname}?podlive=${id}`;
    shareInProgress = true;
    try {
        if (navigator.share) await navigator.share({ title, text: `Join ${title} live on PodLive`, url });
        else { await navigator.clipboard.writeText(url); window.alert('Live link copied'); }
    } catch (error) {
        // Closing the native share sheet is a normal user action, not an app error.
        if (!['AbortError', 'InvalidStateError'].includes(error?.name)) console.warn('Unable to share PodLive link', error);
    } finally {
        shareInProgress = false;
    }
};

function Viewer({ id, back, realtime }) {
    const [state, setState] = useState({ loading: true, room: null, details: null, error: '' });
    const [chatMode, setChatMode] = useState('panel');
    const connect = useCallback(async () => { setState((current) => ({ ...current, loading: true, error: '' })); try { const [room, details] = await Promise.all([podlive.viewerToken(id), podlive.details(id)]); setState({ loading: false, room, details, error: '' }); } catch (error) { const ended = error?.response?.status === 404; setState({ loading: false, room: null, details: null, error: ended ? 'This live room has ended.' : unwrapApiError(error) }); } }, [id]);
    useEffect(() => { connect(); const ended = (event) => { if (event.detail?.sessionId === id) back(); }; window.addEventListener('podlive:ended', ended); return () => window.removeEventListener('podlive:ended', ended); }, [back, connect, id]);
    useEffect(() => { if (state.error.includes('ended')) back(); }, [back, state.error]);
    if (state.loading) return <Loading label="Joining live room…"/>;
    if (state.error?.includes('ended')) return null;
    if (state.error) return <div className="mx-auto max-w-xl p-5"><ErrorBox text={state.error} retry={connect}/></div>;
    return <div className="flex h-full min-h-0 flex-col bg-black"><div className="flex min-h-14 shrink-0 flex-wrap items-center justify-between gap-2 border-b border-white/10 px-3 py-2"><button onClick={back} className="flex items-center gap-2 rounded-full bg-white/10 px-3 py-2 text-xs font-bold"><ArrowLeftIcon className="h-4 w-4"/>Leave podcast</button><div className="flex items-center gap-2"><span className="text-xs text-zinc-300">{realtime.viewerCount} watching</span><button onClick={() => setChatMode(chatMode==='panel'?'overlay':'panel')} className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold"><ChatBubbleLeftRightIcon className="mr-1 inline h-4 w-4"/>{chatMode==='overlay'?'Side chat':'Chat over video'}</button>{chatMode==='hidden'&&<button onClick={()=>setChatMode('panel')} className="rounded-full bg-white/10 p-2" aria-label="Show chat"><EyeIcon className="h-4 w-4"/></button>}<button onClick={() => shareLive(id, state.details?.title)} className="rounded-full bg-white/10 p-2"><ShareIcon className="h-4 w-4"/></button><span className="rounded bg-red-600 px-2 py-1 text-[10px] font-black">● LIVE</span></div></div><div className="flex min-h-0 flex-1 flex-col md:flex-row"><div className="relative min-h-0 flex-1"><React.Suspense fallback={<Loading label="Connecting…"/>}><LiveRoom token={state.room.token} serverUrl={state.room.livekitUrl} onDisconnected={back}/></React.Suspense>{chatMode==='overlay'&&<ChatPanel realtime={realtime} overlay onClose={()=>setChatMode('hidden')}/>}</div>{chatMode==='panel'&&<ChatPanel realtime={realtime} onClose={()=>setChatMode('hidden')}/>}</div></div>;
}

function Studio({ id, back, realtime }) {
    const [state, setState] = useState({ room: null, loading: true, error: '' });
    const [handle, setHandle] = useState(''); const [guests, setGuests] = useState([]); const [notice, setNotice] = useState('');
    const [panel, setPanel] = useState('controls');
    const connect = useCallback(async () => { setState({ room: null, loading: true, error: '' }); try { setState({ room: await podlive.start(id), loading: false, error: '' }); } catch (error) { setState({ room: null, loading: false, error: unwrapApiError(error) }); } }, [id]);
    const loadGuests = useCallback(() => podlive.guests(id).then((data) => setGuests(Array.isArray(data) ? data : data.guests || [])).catch(() => {}), [id]);
    useEffect(() => { connect(); loadGuests(); const timer = setInterval(loadGuests, 5000); return () => clearInterval(timer); }, [connect, loadGuests]);
    const invite = (event) => { event.preventDefault(); if (!handle.trim()) return; realtime.sendInvite(handle); setHandle(''); };
    useEffect(() => { if (realtime.inviteStatus) setNotice(realtime.inviteStatus.message || (realtime.inviteStatus.success ? 'Invite sent.' : 'Could not send invite.')); }, [realtime.inviteStatus]);
    const control = async (action, userId) => { await action(id, userId); loadGuests(); };
    const [ending, setEnding] = useState(false);
    const end = async () => { if (ending) return; setEnding(true); try { await podlive.end(id); } catch (error) { if (![404, 409].includes(error?.response?.status)) console.warn('PodLive end request failed', error); } finally { feedCache = []; back(); } };
    if (state.loading) return <Loading label="Preparing camera and microphone…"/>;
    if (state.error) return <div className="mx-auto max-w-xl p-5"><ErrorBox text={state.error} retry={connect}/></div>;
    const controls = <aside className="flex min-h-0 w-full shrink-0 flex-col border-t border-white/10 bg-zinc-950 xl:w-96 xl:border-l xl:border-t-0"><div className="flex border-b border-white/10"><button onClick={()=>setPanel('controls')} className={`flex-1 px-3 py-3 text-xs font-black ${panel==='controls'?'border-b-2 border-indigo-500 text-white':'text-zinc-500'}`}><AdjustmentsHorizontalIcon className="mr-1 inline h-4 w-4"/>Controls</button><button onClick={()=>setPanel('chat')} className={`flex-1 px-3 py-3 text-xs font-black ${panel==='chat'?'border-b-2 border-indigo-500 text-white':'text-zinc-500'}`}><ChatBubbleLeftRightIcon className="mr-1 inline h-4 w-4"/>Chat</button><button onClick={()=>setPanel('hidden')} className="px-3 text-zinc-500" aria-label="Hide panel"><XMarkIcon className="h-5 w-5"/></button></div>{panel==='chat'?<ChatPanel realtime={realtime}/>:<div className="min-h-0 flex-1 overflow-y-auto p-4"><h3 className="font-black">Invite to stage</h3><form onSubmit={invite} className="mt-3 flex gap-2"><input value={handle} onChange={(e) => setHandle(e.target.value)} required placeholder="@username" className="min-w-0 flex-1 rounded-lg border border-white/10 bg-zinc-900 px-3 py-2 text-sm outline-none focus:border-indigo-500"/><button className="rounded-lg bg-indigo-600 px-3 text-xs font-bold">Invite</button></form>{notice&&<p className="mt-2 text-xs text-zinc-400">{notice}</p>}<h4 className="mt-5 text-xs font-black uppercase tracking-wider text-zinc-500">On stage ({guests.length})</h4><div className="mt-2 space-y-2">{guests.length?guests.map((guest)=>{const user=guest.invitee||guest.user||guest;return <div key={guest.id||user.id} className="rounded-xl border border-white/[.07] bg-white/5 p-3"><p className="truncate text-sm font-bold">{user.display_name||user.unique_handle}</p><div className="mt-2 grid grid-cols-3 gap-1"><button onClick={()=>control(podlive.muteGuest,user.id)} className="rounded bg-white/10 px-2 py-2 text-[10px]">Mute mic</button><button onClick={()=>control(podlive.disableGuestCamera,user.id)} className="rounded bg-white/10 px-2 py-2 text-[10px]">Camera off</button><button onClick={()=>control(podlive.removeGuest,user.id)} className="rounded bg-red-600/30 px-2 py-2 text-[10px] text-red-300">Remove</button></div></div>}):<p className="py-4 text-xs text-zinc-600">No guests on stage.</p>}</div></div>}</aside>;
    return <div className="flex h-full min-h-0 flex-col bg-black"><div className="flex min-h-14 shrink-0 flex-wrap items-center justify-between gap-2 border-b border-white/10 px-3 py-2"><span className="font-black text-red-500">● LIVE · {realtime.viewerCount} watching</span><div className="flex flex-wrap gap-2"><button onClick={()=>setPanel(panel==='overlay'?'chat':'overlay')} className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold"><ChatBubbleLeftRightIcon className="mr-1 inline h-4 w-4"/>{panel==='overlay'?'Side chat':'Chat over video'}</button>{panel==='hidden'&&<button onClick={()=>setPanel('controls')} className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold">Show panel</button>}<button onClick={()=>shareLive(id,'Live podcast')} className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold">Share</button><button onClick={end} disabled={ending} className="rounded-full bg-red-600 px-4 py-2 text-xs font-black disabled:opacity-50">{ending?'Ending…':'End for everyone'}</button></div></div><div className="flex min-h-0 flex-1 flex-col xl:flex-row"><div className="relative min-h-0 flex-1"><React.Suspense fallback={<Loading label="Opening studio…"/>}><LiveRoom token={state.room.token} serverUrl={state.room.livekitUrl} publisher onDisconnected={() => setState((current) => ({ ...current, error: 'Connection lost. Rejoin the same live room.' }))}/></React.Suspense>{panel==='overlay'&&<ChatPanel realtime={realtime} overlay onClose={()=>setPanel('hidden')}/>}</div>{panel!=='hidden'&&panel!=='overlay'&&controls}</div></div>;
}

function GuestRoom({ room, back, realtime }) {
    const [chatMode, setChatMode] = useState('panel');
    return <div className="flex h-full min-h-0 flex-col bg-black text-white"><header className="flex min-h-14 shrink-0 items-center justify-between gap-2 border-b border-white/10 px-3 py-2"><span className="font-black text-red-500">● ON STAGE</span><div className="flex gap-2"><button onClick={()=>setChatMode(chatMode==='overlay'?'panel':'overlay')} className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold">{chatMode==='overlay'?'Side chat':'Chat over video'}</button>{chatMode==='hidden'&&<button onClick={()=>setChatMode('panel')} className="rounded-full bg-white/10 px-3 py-2 text-xs font-bold">Show chat</button>}<button onClick={back} className="rounded-full bg-red-600 px-4 py-2 text-xs font-black">Leave podcast</button></div></header><div className="flex min-h-0 flex-1 flex-col md:flex-row"><div className="relative min-h-0 flex-1"><React.Suspense fallback={<Loading label="Joining stage…"/>}><LiveRoom token={room.token} serverUrl={room.livekitUrl} publisher onDisconnected={back}/></React.Suspense>{chatMode==='overlay'&&<ChatPanel realtime={realtime} overlay onClose={()=>setChatMode('hidden')}/>}</div>{chatMode==='panel'&&<ChatPanel realtime={realtime} onClose={()=>setChatMode('hidden')}/>}</div></div>;
}

function Upload({ open }) {
    const [values, setValues] = useState({ title: '', description: '', category: 'Technology' });
    const [file, setFile] = useState(null); const [thumbnail, setThumbnail] = useState(null); const [thumbnailPreview, setThumbnailPreview] = useState('');
    const [progress, setProgress] = useState(0); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
    useEffect(() => { if (!thumbnail) { setThumbnailPreview(''); return undefined; } const url = URL.createObjectURL(thumbnail); setThumbnailPreview(url); return () => URL.revokeObjectURL(url); }, [thumbnail]);
    const submit = async (event) => { event.preventDefault(); if (!file || busy) return; setBusy(true); setError(''); const form = new FormData(); Object.entries(values).forEach(([key, value]) => form.append(key, value)); form.append('video', file); if (thumbnail) form.append('thumbnail', thumbnail); try { await podlive.uploadVideo(form, setProgress); feedCache = []; open('dashboard'); } catch (err) { setError(unwrapApiError(err)); setBusy(false); } };
    return <div className="mx-auto max-w-4xl p-4 pb-24 md:p-7"><h1 className="mb-1 text-2xl font-black">Upload video</h1><p className="mb-6 text-sm text-zinc-500">Publish a video with the same details and thumbnail options as PodLive.</p><form onSubmit={submit} className="grid gap-5 lg:grid-cols-[1fr_18rem]"><div className="space-y-4 rounded-2xl border border-white/10 bg-white/[.03] p-5">{error&&<ErrorBox text={error}/>}<Field label="Title" required value={values.title} onChange={(e)=>setValues({...values,title:e.target.value})}/><label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400">Description<textarea rows="4" value={values.description} onChange={(e)=>setValues({...values,description:e.target.value})} className="mt-2 w-full resize-none rounded-xl border border-white/10 bg-zinc-900 p-4 text-sm text-white outline-none focus:border-indigo-500"/></label><label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400">Category<select value={values.category} onChange={(e)=>setValues({...values,category:e.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-zinc-900 p-3 text-sm text-white">{PODLIVE_CATEGORIES.map((item)=><option key={item}>{item}</option>)}</select></label><label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400">Thumbnail image<div className="mt-2 grid min-h-36 cursor-pointer place-items-center overflow-hidden rounded-xl border border-dashed border-white/15 bg-zinc-900 text-center hover:border-indigo-500/60">{thumbnailPreview?<img src={thumbnailPreview} alt="Thumbnail preview" className="aspect-video h-full w-full object-cover"/>:<span className="px-4 text-sm normal-case text-zinc-500">Choose JPG, PNG or WebP thumbnail</span>}</div><input type="file" accept="image/*" onChange={(e)=>setThumbnail(e.target.files?.[0]||null)} className="mt-2 block w-full text-sm normal-case"/></label></div><aside className="h-fit space-y-4 rounded-2xl border border-white/10 bg-white/[.03] p-5"><label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400">Video file<input type="file" accept="video/mp4,video/webm,video/quicktime,video/x-msvideo" required onChange={(e)=>setFile(e.target.files?.[0]||null)} className="mt-3 block w-full text-sm normal-case"/></label>{file&&<p className="break-all text-xs text-zinc-400">{file.name}</p>}{progress>0&&<div><div className="h-2 overflow-hidden rounded bg-zinc-800"><div className="h-full bg-indigo-500 transition-all" style={{width:`${progress}%`}}/></div><p className="mt-1 text-xs">{progress}% uploaded</p></div>}<button disabled={busy} className="w-full rounded-xl bg-indigo-600 py-3 font-black disabled:opacity-50">{busy?'Uploading…':'Publish video'}</button><div className="space-y-1 text-xs text-zinc-500"><p>✓ Custom thumbnail</p><p>✓ Adaptive video processing</p><p>✓ Published to your profile</p></div></aside></form></div>;
}

function VideoViewer({id,back}) { const [item,setItem]=useState(null); const [following,setFollowing]=useState(false); const [comment,setComment]=useState(''); useEffect(()=>{podlive.details(id).then((data)=>{setItem(data);podlive.followStatus(data.host.id).then((s)=>setFollowing(s.following)).catch(()=>{});}).catch(()=>setItem(false));podlive.view(id).catch(()=>{});},[id]); const like=async()=>{const result=await podlive.like(id);setItem((v)=>({...v,like_count:result.like_count}));}; const follow=async()=>{const result=await podlive.follow(item.host.id);setFollowing(result.following);}; const post=async(e)=>{e.preventDefault();if(!comment.trim())return;const result=await podlive.comment(id,comment);setItem((v)=>({...v,chat_messages:[...(v.chat_messages||[]),result.comment]}));setComment('');}; if(item===null)return <Loading label="Loading video…"/>; if(!item)return <ErrorBox text="Video unavailable" retry={back}/>; return <div className="mx-auto max-w-5xl p-4"><button onClick={back} className="mb-3 text-sm">← Back</button><React.Suspense fallback={<Loading label="Opening player…"/>}><UploadedVideoPlayer src={item.recording_url} poster={item.thumbnail_url}/></React.Suspense><h1 className="mt-4 text-xl font-black">{item.title}</h1><div className="mt-2 flex flex-wrap items-center gap-2"><p className="mr-auto text-sm text-zinc-500">{item.views||0} views · {item.like_count||0} likes · {item.chat_messages?.length||0} comments</p><button onClick={follow} className="rounded-full bg-white/10 px-4 py-2 text-xs font-bold">{following?'Following':'Follow'}</button><button onClick={like} className="rounded-full bg-indigo-600 px-4 py-2 text-xs font-bold">Like · {item.like_count||0}</button></div><section className="mt-6 border-t border-white/10 pt-4"><form onSubmit={post} className="flex gap-2"><input value={comment} onChange={(e)=>setComment(e.target.value)} maxLength="500" placeholder="Add a comment" className="min-w-0 flex-1 rounded-full bg-zinc-900 px-4 py-2 text-sm"/><button className="rounded-full bg-indigo-600 px-4 text-xs font-bold">Post</button></form><div className="mt-4 space-y-3">{(item.chat_messages||[]).map((entry)=><div key={entry.id} className="rounded-xl bg-white/5 p-3 text-sm"><b className="mr-2 text-indigo-400">{entry.sender_handle}</b>{entry.message}</div>)}</div></section></div>; }

function Create({ open, cheetchatToken }) {
    const [values, setValues] = useState({ title: '', description: '', category: 'Technology' }); const [thumbnail, setThumbnail] = useState(null); const [preview, setPreview] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
    useEffect(()=>{if(!thumbnail){setPreview('');return undefined;}const url=URL.createObjectURL(thumbnail);setPreview(url);return()=>URL.revokeObjectURL(url);},[thumbnail]);
    const submit = async (event) => { event.preventDefault(); if(busy)return; setBusy(true); setError(''); try { let thumbnailUrl=''; if(thumbnail){const upload=new FormData();upload.append('file',thumbnail);const headers=cheetchatToken&&cheetchatToken!=='cookie-session'?{Authorization:`Bearer ${cheetchatToken}`}:{ };const response=await axios.post('/api/upload',upload,{headers,timeout:120000});thumbnailUrl=response.data.url;} const result = await podlive.create({ ...values, visibility:'public', goLiveNow:true, dvr_enabled:false, thumbnail_url:thumbnailUrl||undefined, thumbnailUrl:thumbnailUrl||undefined }); feedCache=[]; open('studio', result.session.id); } catch (err) { setError(unwrapApiError(err)); setBusy(false); } };
    return <div className="mx-auto max-w-2xl p-4 pb-24 md:p-8"><h1 className="mb-6 text-2xl font-black">Start live</h1><form onSubmit={submit} className="space-y-5 rounded-3xl border border-white/10 bg-white/[.04] p-5 md:p-7">{error && <ErrorBox text={error}/>}<Field label="Title" required maxLength="120" value={values.title} onChange={(event) => setValues({...values, title:event.target.value})}/><label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400">Description<textarea rows="4" maxLength="1000" value={values.description} onChange={(event) => setValues({...values, description:event.target.value})} className="mt-2 w-full resize-none rounded-xl border border-white/10 bg-zinc-900 p-4 text-sm text-white outline-none focus:border-indigo-500"/></label><label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400">Category<select value={values.category} onChange={(event) => setValues({...values, category:event.target.value})} className="mt-2 w-full rounded-xl border border-white/10 bg-zinc-900 p-3 text-sm text-white">{PODLIVE_CATEGORIES.map((item) => <option key={item}>{item}</option>)}</select></label><label className="block text-xs font-semibold uppercase tracking-wider text-zinc-400">Podcast thumbnail<div className="mt-2 grid aspect-video cursor-pointer place-items-center overflow-hidden rounded-2xl border border-dashed border-white/15 bg-zinc-900">{preview?<img src={preview} alt="Podcast thumbnail preview" className="h-full w-full object-cover"/>:<span className="px-4 text-center text-sm normal-case text-zinc-500">Choose an image viewers will see in the Live Now feed</span>}</div><input type="file" accept="image/*" onChange={(event)=>setThumbnail(event.target.files?.[0]||null)} className="mt-2 block w-full text-sm normal-case"/></label><p className="text-xs text-zinc-500">This public podcast appears in Live Now for every PodLive user.</p><button disabled={busy} className="w-full rounded-xl bg-red-600 py-3 font-black disabled:opacity-50">{busy ? 'Starting…' : 'Go Live'}</button></form></div>;
}

function Dashboard({ open }) {
    const [stats, setStats] = useState(null); const [videos,setVideos]=useState([]); useEffect(() => { Promise.all([podlive.stats(),podlive.profile(),podlive.videos()]).then(([nextStats,profile,all])=>{setStats(nextStats);setVideos(all.filter((item)=>item.host_user_id===profile.id));}).catch(() => setStats({})); }, []);
    const cards = [['Followers', stats?.followers], ['Total views', stats?.totalViews], ['Live sessions', stats?.totalLives]];
    return <div className="mx-auto max-w-6xl space-y-7 p-4 pb-24 md:p-7"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-black">Creator Studio</h1><p className="text-xs text-zinc-500">Audience and content analytics</p></div><div className="flex gap-2"><button onClick={() => open('upload')} className="rounded-full bg-indigo-600 px-5 py-2 text-xs font-black">Upload video</button><button onClick={() => open('create')} className="rounded-full bg-red-600 px-5 py-2 text-xs font-black">Go Live</button></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{[...cards,['Videos',stats?.totalVideos],['Likes',stats?.totalLikes]].map(([label,value]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/[.04] p-5"><p className="text-xs uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-2 text-2xl font-black">{Number(value || 0).toLocaleString()}</p></div>)}</div><section><h2 className="mb-3 text-lg font-black">Your videos</h2>{videos.length?<div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{videos.map((item)=><VideoCard key={item.id} video={item} open={open}/>)}</div>:<Empty text="You have not uploaded a video yet."/>}</section></div>;
}

export default function PodLiveApp({ active, onBack, incomingInvite = null, onInviteConsumed, cheetchatToken }) {
    const initialId = new URLSearchParams(window.location.search).get('podlive');
    const session = usePodLiveSession(active); const [route, setRoute] = useState(initialId ? { name: 'live', id: initialId } : { name: 'browse', id: null });
    const open = useCallback((name, id = null, room = null) => { const next = { name, id, ...(room && { room }) }; window.history.pushState({ podliveRoute: { name, id } }, ''); setRoute(next); }, []);
    const goBack = useCallback(() => window.history.back(), []);
    const goBrowse = goBack;
    const goDashboard = goBack;
    const realtime = usePodLiveSocket(route.id, session.user);
    useEffect(() => {
        window.history.pushState({ podliveRoot: true }, '');
        if (initialId) window.history.pushState({ podliveRoute: { name: 'live', id: initialId } }, '');
        const handleBack = (event) => {
            if (event.state?.podliveRoute) setRoute(event.state.podliveRoute);
            else if (event.state?.podliveRoot) setRoute({ name: 'browse', id: null });
            else onBack();
        };
        window.addEventListener('popstate', handleBack);
        return () => window.removeEventListener('popstate', handleBack);
    }, []);
    useEffect(() => { const ended = (event) => { if (route.name === 'guest' && event.detail?.sessionId === route.id) goBack(); }; window.addEventListener('podlive:ended', ended); return () => window.removeEventListener('podlive:ended', ended); }, [goBack, route.name, route.id]);
    if (!active) return null;
    const content = route.name === 'browse' ? <Browse open={open}/> : route.name === 'live' ? <Viewer id={route.id} back={goBrowse} realtime={realtime}/> : route.name === 'studio' ? <Studio id={route.id} back={goDashboard} realtime={realtime}/> : route.name === 'create' ? <Create open={open} cheetchatToken={cheetchatToken}/> : route.name === 'upload' ? <Upload open={open}/> : route.name === 'video' ? <VideoViewer id={route.id} back={goBrowse}/> : <Dashboard open={open}/>;
    const activeInvite = incomingInvite || realtime.invite;
    const clearActiveInvite = () => { realtime.clearInvite(); onInviteConsumed?.(); };
    const accept = async () => { const invite = activeInvite; const result = await podlive.upgradeToken(invite.sessionId); realtime.respondToInvite('accept_invite', { sessionId: invite.sessionId, hostId: invite.host?.id, inviteeHandle: session.user?.unique_handle }); clearActiveInvite(); open('guest', invite.sessionId, result); };
    if (route.name === 'guest' && route.room) return <GuestRoom room={route.room} realtime={realtime} back={goBack}/>;
    if (session.loading && !session.user) return <div className="h-full bg-[#080808] text-white"><Loading label="Opening PodLive…"/></div>;
    if (session.error && !session.user) return <div className="grid h-full place-items-center bg-[#080808] p-4 text-white"><ErrorBox text={session.error} retry={session.retry}/></div>;
    if (route.name === 'studio' || route.name === 'live') return <div className="h-full bg-black text-white">{content}</div>;
    const inviteModal = activeInvite && <div className="fixed inset-0 z-[100] grid place-items-center bg-black/70 p-4"><div className="w-full max-w-sm rounded-2xl bg-zinc-900 p-5 text-center"><UserGroupIcon className="mx-auto h-10 w-10 text-indigo-400"/><h2 className="mt-3 text-xl font-black">Stage invitation</h2><p className="mt-2 text-sm text-zinc-400">{activeInvite.host?.display_name} invited you to join the live podcast.</p><div className="mt-5 flex gap-2"><button onClick={()=>{realtime.respondToInvite('reject_invite',{sessionId:activeInvite.sessionId,hostId:activeInvite.host?.id,inviteeHandle:session.user?.unique_handle});clearActiveInvite();}} className="flex-1 rounded-xl bg-white/10 py-2 font-bold">Decline</button><button onClick={accept} className="flex-1 rounded-xl bg-indigo-600 py-2 font-bold">Join stage</button></div></div></div>;
    return <div className="flex h-full flex-col overflow-hidden bg-[#080808] text-white">{inviteModal}<header className="flex h-14 shrink-0 items-center gap-3 border-b border-white/[.07] px-3"><button onClick={onBack} className="rounded-full p-2"><ArrowLeftIcon className="h-5 w-5"/></button><button onClick={() => open('browse')} className="flex items-center gap-2 font-black"><span className="grid h-8 w-8 place-items-center rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600"><MicrophoneIcon className="h-4 w-4"/></span><span>PodLive</span></button><nav className="ml-auto flex items-center gap-1"><button onClick={() => open('browse')} className="rounded-full px-3 py-2 text-xs font-bold"><SignalIcon className="inline h-4 w-4 sm:mr-1"/><span className="hidden sm:inline">Home</span></button><button onClick={() => open('upload')} className="rounded-full px-3 py-2 text-xs font-bold"><VideoCameraIcon className="inline h-4 w-4 sm:mr-1"/><span className="hidden sm:inline">Upload</span></button><button onClick={() => open('dashboard')} className="rounded-full px-3 py-2 text-xs font-bold"><UserGroupIcon className="inline h-4 w-4 sm:mr-1"/><span className="hidden sm:inline">Studio</span></button><img src={avatarFor(session.user)} alt="" className="ml-1 h-8 w-8 rounded-full object-cover"/></nav></header><main className="min-h-0 flex-1 overflow-y-auto">{content}</main></div>;
}
